[package]
name = "aoc_2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graph = "0.3.1"
itertools = "0.12.0"
pathfinding = "4.6.0"
regex = "1.10.2"
